### PR TITLE
Updated Fabric to 1.19

### PR DESCRIPTION
**Pull request by seeruk**
I think this covers everything, it all seems to be working fine in-game to me!

### CODE REVIEW

**Comment by Godols** [comment]
Hey Seer, I really want to do what you did to get the mod in 1.19, but I really don't know how to do that (never really experimented with code and whatnot). How do you modify the 1.18.2 fabric version for it to be compatible in 1.19? Thanks!

**Comment by seeruk** [comment]
[chipped-1.2+1.19.zip](https://github.com/terrarium-earth/Chipped/files/9163278/chipped-1.2%2B1.19.zip)

Here's the compiled version, I'll remove it if the authors aren't happy with it being posted here though. Full disclosure, I am not a maintainer of Chipped, I compiled this myself after making the changes you see in this PR, but you'll get no support from the mod authors for this version of the mod, so please don't ask them about it if there are problems. Enjoy!

**Comment by Godols** [comment]
Dude, that's awesome! Thanks so much! I've been eyeing this mod since forever for 1.19, and you just saved me! I love you! (jk on that last part)

No but for real, I didn't even expect a response back. Thanks so much man. And yeah, I understand if the devs want you to delete it, but honestly, you just did the work for them it seems like, haha.

**Comment by eliskvitka** [comment]
Thank you. Works fine on Fabric 1.19.2

**Comment by CodexAdrian** [comment]
Chipped 1.19 will be a rewrite, and will not have separate branches for forge and fabric

**Pull request closed without merging**
